### ISSUE TITLE
 Support more names for all fields ("image", "images", "photo", etc), create waterfall logic

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-open-graph#6]
Support a few more variations when trying to get the image for use in Open Graph.

Common field names are "image" and "images", but it could also be "header", "photo", "carousel", etc. Look into this and figure out some more names to fallback on (to make it work on even more sites without them needed to change their config).

**Comment by selbekk** [comment]
Could we add a config for these? What works in our projects might not work for others, and creating an exhaustive list of field names is near to impossible (at very best impractical). 

I suggest that we could add a basic config file that contains our current fallbacks, but that can be changed programmatically from project to project if they need to be changed.

**Comment by Bellfalasch** [comment]
That's a brilliant idea =)

May I suggest an "append" approach? We define 2-3 most comment names of fields, but let user via site.xml add a comma separated list of more names. Concat that and ours to a string, split into an array, and just check "if in array". Would make code even smoother too!

**Comment by Bellfalasch** [comment]
I'm on this issue now, will try to get it into a 1.0.0 release. Added 3 settings for the different user defined paths (one for each of title, description and image). Will be set by the user as a comma separated list and then used in the code's "waterfall" logic for selecting the right data to use.

**Comment by Bellfalasch** [comment]
Finished by adding two functions now used in all "getPageX" functions. The first one splits on comma but also does some trimming. The next one will loop through this array and match it towards the json and stop on first match and return its value.
