### ISSUE TITLE
"app-open-graph" is now a poor name

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-open-graph#8]
Since we are adding SEO-stuff in general, and might also later add Twitter Cards, this app's name would have worked better named something else. SEO/Social app?

**Comment by selbekk** [comment]
Agree that the name is somewhat misleading now. 

I'm suggesting `seo-fields` or `meta-fields`.

**Comment by Bellfalasch** [comment]
Meta-fields might be something. It gives SEO capabilities and social meta data, so it could be "social and seo app", but the essence of it is adding and manipulating meta data.

Changing name of app will loose all data connected to it.

**Comment by Michael-Lazell** [comment]
I'm sure Thomas will have an opinion on this.



Best regards
Enonic AS

Michael Lazell
Services Manager Americas

Mobile +1 (415) 774-6090
Norwegian office +47 22 00 85 50

https://enonic.com - A web operating system for your sites and applications

**Comment by Bellfalasch** [comment]
Perhaps do something as easy as also adding favicon-setting/upload and rename the app to "site-essentials" which is basically what it is. Things you'll add to all sites you're working on.

?

**Comment by selbekk** [comment]
Good idea @Bellfalasch :+1:

**Comment by Bellfalasch** [comment]
Thinking more about it, and looking more into it, I recon a favicon app should be its own self contained app. There are a lot of things with mobile icons to consider at the same time and bundling all that into one single favicon super app would be very handy.

Which leaves us with this app being mostly for seo and social meta / open graph. So "seo-fields" might be a better name for it then. Something that would instantly tell a potential user that "hey, this app is for controlling open graph and seo things". Damn that mixin ... would be best as two parts, but then we would have duplicate mixin.

**Comment by Bellfalasch** [comment]
SEO Meta Fields will be the new name. It describes the app in a better way since it adds and controls meta data fields related to SEO.
