### ISSUE TITLE
Use as lib instead of app

### ISSUE THREAD

**Issue by selbekk** [enonic/app-open-graph#9]
Why should this be an application and not a library?

According to [this answer](https://discuss.enonic.com/t/how-to-depend-on-applications/335/4) from @sigdestad, applying it as a library should not be a problem. It shouldn't be started as its own application, since it doesn't make sense on its own.

**Comment by selbekk** [comment]
Also, how can it be used as a library? I would assume it needs to be built and deployed somewhere?

**Comment by sigdestad** [comment]
If it adds value when added to a site it sure can be an app, but it can be a library too if it is intended for reuse. If it is supposed to be customized per app, simply include the library and overwrite the files you want in your app.

Vennlig hilsen/Best regards 

Thomas Sigdestad

**Comment by sigdestad** [comment]
Must be installed to a maven repo such as repo.enonic.com.. There are also free public repos out there!

Vennlig hilsen/Best regards 

Thomas Sigdestad
CTO & Co-Founder
+47 98236011

https://enonic.com - A web operating system for your sites and applications

**Comment by selbekk** [comment]
I guess this application doesn't add anything that a site can't do without, so it could indeed be used as an application. In my opinion it should be available as a library too though, so that the consumer can choose how to use it.

**Comment by Bellfalasch** [comment]
I have the tools to do this locally (get the app into our repo). Will look into that when releasing. Locking this issue as I will keep this as an app.
